### ISSUE TITLE
Formula are not displayed correctly.

### ISSUE THREAD

**Issue by zzxiang** [DAGfans/DAGfans.github.io#1]
The formula in [https://dagfans.org/paper/2018/07/09/PHANTOM-5-PROOF.html](https://dagfans.org/paper/2018/07/09/PHANTOM-5-PROOF.html) are not displayed correctly.

![image](https://user-images.githubusercontent.com/10098144/44943393-ad911680-ae00-11e8-94a3-0fbfe1724223.png)

**Comment by zzxiang** [comment]
The math formula display feature is provided by [MathJax](https://www.mathjax.org/).

Commit c89bc22cc18c605831c6cc53baf5d8d89244e9f1

**Comment by zzxiang** [comment]
Seems that using the [math block syntax of kramdown](https://kramdown.gettalong.org/syntax.html#math-blocks) can solve the problem. Kramdown uses `$$...$$` to mark both math blocks and inline math formula.

You can use `:%s/\(\$\)\@<!\$\(\$\)\@!/$$/g` to replace `$` with `$$` in Vim.

**Comment by forchain** [comment]
MathJax supports double dollar signs either, which is for separate line use ( single dollar is for in-line use). So would it have conflicts with Kramdown?

**Comment by zzxiang** [comment]
Actually kramdown also uses MathJax as its render engine. I've tested locally. Seems that there's no problem.

**Comment by zzxiang** [comment]
Commit eb1cbf8f4add7571bee09fda026fce99db139fab solved the issue.

**Comment by forchain** [comment]
Verified.
