### ISSUE TITLE
Certificate failed?

### ISSUE THREAD

**Issue by zzxiang** [DAGfans/DAGfans.github.io#2]
When I access https://dagfans.org/ I get a privacy error saying "Your connection is not private".

![image](https://user-images.githubusercontent.com/10098144/44950620-2fc41e00-ae87-11e8-8ce9-71fa524ad8a9.png)

**Comment by forchain** [comment]
I think, I need update the certificate, would you please help me with it?

**Comment by zzxiang** [comment]
OK, I've updated it.
